// Generated by CoffeeScript 1.9.3
module.exports = function(target) {
  if (typeof target === 'string') {
    return document.getElementById(target) || document.querySelector(target);
  }
  return target;
};
