// Generated by CoffeeScript 1.9.3
(function() {
  return module.exports = function(element, options) {
    element = require('./_element')(element);
    element.setAttribute("href", (require('./line-url'))(options));
    element.setAttribute("target", "_blank");
    element.addEventListener('click', function() {
      require('./line-send')(options);
      return false;
    });
    return element.addEventListener('touchend', function() {
      require('./line-send')(options);
      return false;
    });
  };
})();
