// Generated by CoffeeScript 1.9.3
(function() {
  return module.exports = function(options) {
    var url;
    url = require('./line-url');
    return window.open(url(options), 'line-send', 'width=600,height=460');
  };
})();
