// Generated by CoffeeScript 1.9.3
(function() {
  return module.exports = function(options) {
    var url;
    url = "http://line.me/R/msg/text/";
    url += options.text;
    return url;
  };
})();
