// Generated by CoffeeScript 1.9.3
(function() {
  return module.exports = function(element, options) {
    element = require('./_element')(element);
    element.setAttribute("href", (require('./line-url'))(options));
    element.setAttribute("target", "_blank");
    return element.onclick = function() {
      require('./line-send')(options);
      return false;
    };
  };
})();
