// Generated by CoffeeScript 1.9.3
(function() {
  return module.exports = function(options) {
    var url;
    url = require('./tweet-url');
    return window.open(url(options), 'twitter-intent', 'width=600,height=460');
  };
})();
